# Generated by Django 5.1.2 on 2024-10-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('company', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField()),
            ],
        ),
    ]
