# Generated by Django 5.1.2 on 2024-12-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobwebsite', '0007_job_tags_alter_applicant_gender_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('full time', 'Full time'), ('part time', 'Part time'), ('internship', 'Internship')], max_length=10),
        ),
    ]
